dist: trusty
language: python
notifications:
  email: false
sudo: false
python:
  - '3.5'
  - '3.6'
  - '3.7'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

# command to install dependencies
install: make setup

# command to run tests
script: make test

after_success: codecov
