dist: xenial
language: python
notifications:
  email: false
sudo: false
python:
  - '3.5'
  - '3.6'
  - '3.7'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

# command to install dependencies
install:
  - travis_retry pip install -U tox-travis
  - make setup

# command to run tests
script: pipenv run -- tox

after_success: pipenv run -- codecov
