dist: xenial
language: python
sudo: false
python:
  - '3.5'
  - '3.6'
  - '3.7'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

# command to install dependencies
install:
  - travis_retry pip install -U tox-travis
  - make init

# command to run tests
script: pipenv run tox -v

after_success: pipenv run codecov
