language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
# command to install dependencies
install:
  - pip install pip --upgrade
  - pip install -r testproject/requirements.txt
# command to run tests
script:
  - testproject/manage.py test
