dist: xenial
language: python
sudo: false
python:
  - '3.5'
  - '3.6'
  - '3.7'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VERBOSITY=-1
    - SECRET_KEY=_

# command to install dependencies
install:
  - travis_retry pip install -U tox-travis

before_script:
    - make init
    - make setup

# command to run tests
script: pipenv run tox -v

after_success: pipenv run codecov
