language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
# command to run tests
script:
  - cp laum/settings.py.sample laum/settings.py
  - sed -i -e "s/SECRET_KEY = '.*'/SECRET_KEY = '$(</dev/urandom | tr -cd 'a-z0-9!@#$%^&*()' | head -c 50)'/g" laum/settings.py
  - ./manage.py migrate
  - ./manage.py collectstatic
  - ./manage.py test
